name: Matlab tests
on: 
  push:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        release: [R2020b, R2021b, R2022b, R2023b]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.release }}
      - uses: matlab-actions/run-tests@v2
        with:
          source-folder: mitc
